version: '3.8'

networks:
  signalseek-netversion: '3.8'

networks:
  signalseek-net:

services:
  postgres:
    image: postgres:17
    container_name: dbms
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - signalseek-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: renart-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8180:8180"
    networks:
      - signalseek-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
    restart: on-failure

volumes:
  postgres_data: